# Generated by Django 5.2.12 on 2026-03-08 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "staff_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique staff identifier",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Staff member full name", max_length=255
                    ),
                ),
                (
                    "phone",
                    models.CharField(help_text="Contact phone number", max_length=20),
                ),
                (
                    "is_on_duty",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether staff member is currently on duty",
                    ),
                ),
                (
                    "current_latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Current latitude",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "current_longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Current longitude",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "last_location_update",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time location was updated",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="User account for this staff member",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff Member",
                "verbose_name_plural": "Staff Members",
                "db_table": "staff_members",
                "ordering": ["name"],
            },
        ),
    ]
