# Generated by Django 5.2.12 on 2026-03-08 18:11

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LocationUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6, help_text="Latitude coordinate", max_digits=9
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6, help_text="Longitude coordinate", max_digits=9
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp of this location update",
                    ),
                ),
                (
                    "accuracy",
                    models.FloatField(
                        blank=True,
                        help_text="GPS accuracy in meters (optional)",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Location Update",
                "verbose_name_plural": "Location Updates",
                "db_table": "location_updates",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.RemoveField(
            model_name="staffmember",
            name="is_on_duty",
        ),
        migrations.AddField(
            model_name="staffmember",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Timestamp when staff member was added",
            ),
        ),
        migrations.AddField(
            model_name="staffmember",
            name="duty_status",
            field=models.CharField(
                choices=[
                    ("on_duty", "On Duty"),
                    ("off_duty", "Off Duty"),
                    ("on_break", "On Break"),
                ],
                db_index=True,
                default="off_duty",
                help_text="Current duty status",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="staffmember",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Whether this staff member is active"
            ),
        ),
        migrations.AlterField(
            model_name="staffmember",
            name="current_latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Current latitude coordinate",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="staffmember",
            name="current_longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Current longitude coordinate",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="staffmember",
            name="last_location_update",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp of last location update", null=True
            ),
        ),
        migrations.AlterField(
            model_name="staffmember",
            name="name",
            field=models.CharField(
                help_text="Full name of the staff member", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="staffmember",
            name="phone",
            field=models.CharField(
                help_text="Contact phone number",
                max_length=17,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="staffmember",
            name="staff_id",
            field=models.CharField(
                db_index=True,
                editable=False,
                help_text="Unique staff identifier (auto-generated)",
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="staffmember",
            name="user",
            field=models.OneToOneField(
                help_text="User account linked to this staff member",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="staffmember",
            index=models.Index(
                fields=["staff_id"], name="staff_membe_staff_i_4b578e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffmember",
            index=models.Index(
                fields=["duty_status"], name="staff_membe_duty_st_d1bfa2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffmember",
            index=models.Index(
                fields=["is_active"], name="staff_membe_is_acti_6ebbb2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffmember",
            index=models.Index(
                fields=["current_latitude", "current_longitude"],
                name="staff_membe_current_716ef1_idx",
            ),
        ),
        migrations.AddField(
            model_name="locationupdate",
            name="staff_member",
            field=models.ForeignKey(
                help_text="Staff member this location update belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="location_updates",
                to="staff.staffmember",
            ),
        ),
        migrations.AddIndex(
            model_name="locationupdate",
            index=models.Index(
                fields=["staff_member", "-timestamp"],
                name="location_up_staff_m_f282d9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="locationupdate",
            index=models.Index(
                fields=["timestamp"], name="location_up_timesta_371544_idx"
            ),
        ),
    ]
