# Generated by Django 5.2.12 on 2026-04-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BinLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bin_id", models.CharField(max_length=50, unique=True)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("address", models.TextField()),
                (
                    "bin_type",
                    models.CharField(
                        choices=[
                            ("general", "General Waste"),
                            ("recyclable", "Recyclable"),
                            ("organic", "Organic"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "collection_schedule",
                    models.TextField(help_text="e.g. Mon, Wed, Fri - 8AM to 12PM"),
                ),
                ("capacity", models.CharField(blank=True, default="", max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "bin_locations",
                "indexes": [
                    models.Index(
                        fields=["bin_type"], name="bin_locatio_bin_typ_a94975_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="bin_locatio_is_acti_63588c_idx"
                    ),
                ],
            },
        ),
    ]
