# Generated by Django 5.2.12 on 2026-03-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="OTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        help_text="Email address for which OTP was generated",
                        max_length=255,
                    ),
                ),
                ("code", models.CharField(help_text="6-digit OTP code", max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="Expiration timestamp (10 minutes from creation)",
                    ),
                ),
                (
                    "is_used",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this OTP has been used",
                    ),
                ),
            ],
            options={
                "verbose_name": "OTP",
                "verbose_name_plural": "OTPs",
                "db_table": "otps",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["email", "is_used"], name="otps_email_a61785_idx"
                    ),
                    models.Index(fields=["expires_at"], name="otps_expires_f6308f_idx"),
                    models.Index(fields=["created_at"], name="otps_created_b35e98_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        help_text="User email address (used for login)",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "is_citizen",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user is a citizen",
                    ),
                ),
                (
                    "is_authority",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether this user is a municipal authority",
                    ),
                ),
                (
                    "is_staff_member",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether this user is a collection staff member",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user account is active",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into admin site",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "users",
                "indexes": [
                    models.Index(fields=["email"], name="users_email_4b85f2_idx"),
                    models.Index(
                        fields=["created_at"], name="users_created_6541e9_idx"
                    ),
                    models.Index(
                        fields=["is_citizen"], name="users_is_citi_1f7024_idx"
                    ),
                    models.Index(
                        fields=["is_authority"], name="users_is_auth_370ac2_idx"
                    ),
                    models.Index(
                        fields=["is_staff_member"], name="users_is_staf_6f057d_idx"
                    ),
                ],
            },
        ),
    ]
