# Generated by Django 5.2.12 on 2026-05-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="has_password",
            field=models.BooleanField(
                default=False, help_text="Whether user has set a password for login"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="prefer_otp",
            field=models.BooleanField(
                default=True, help_text="Whether user prefers OTP login over password"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                blank=True,
                help_text="Password for traditional login (optional, can use OTP instead)",
                max_length=128,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["has_password"], name="users_has_pas_98620f_idx"
            ),
        ),
    ]
