# Generated by Django 5.2.12 on 2026-03-08 15:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("staff", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Complaint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "complaint_id",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        help_text="Unique complaint identifier (auto-generated)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Complaint description (10-500 characters)",
                        validators=[
                            django.core.validators.MinLengthValidator(10),
                            django.core.validators.MaxLengthValidator(500),
                        ],
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Latitude coordinate (-90 to 90)",
                        max_digits=9,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Longitude coordinate (-180 to 180)",
                        max_digits=9,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("assigned", "Assigned"),
                            ("in-progress", "In Progress"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Current status of the complaint",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when complaint was created",
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when staff was assigned",
                        null=True,
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when complaint was resolved",
                        null=True,
                    ),
                ),
                (
                    "response_time",
                    models.DurationField(
                        blank=True,
                        help_text="Time taken from creation to resolution",
                        null=True,
                    ),
                ),
                (
                    "assigned_staff",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff member assigned to this complaint",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_complaints",
                        to="staff.staffmember",
                    ),
                ),
                (
                    "citizen",
                    models.ForeignKey(
                        help_text="Citizen who filed the complaint",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="complaints",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Complaint",
                "verbose_name_plural": "Complaints",
                "db_table": "complaints",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ComplaintPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        help_text="Photo file (max 5MB)",
                        upload_to="complaints/%Y/%m/%d/",
                    ),
                ),
                (
                    "photo_type",
                    models.CharField(
                        choices=[("before", "Before"), ("after", "After")],
                        db_index=True,
                        default="before",
                        help_text="Type of photo (before/after)",
                        max_length=10,
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when photo was uploaded"
                    ),
                ),
                (
                    "complaint",
                    models.ForeignKey(
                        help_text="Complaint this photo belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="complaints.complaint",
                    ),
                ),
            ],
            options={
                "verbose_name": "Complaint Photo",
                "verbose_name_plural": "Complaint Photos",
                "db_table": "complaint_photos",
                "ordering": ["uploaded_at"],
            },
        ),
        migrations.AddIndex(
            model_name="complaint",
            index=models.Index(
                fields=["complaint_id"], name="complaints_complai_c70619_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="complaint",
            index=models.Index(
                fields=["status", "created_at"], name="complaints_status_f38b8e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="complaint",
            index=models.Index(
                fields=["citizen", "status"], name="complaints_citizen_b3cfb0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="complaint",
            index=models.Index(
                fields=["assigned_staff", "status"],
                name="complaints_assigne_75e7cf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="complaint",
            index=models.Index(
                fields=["latitude", "longitude"], name="complaints_latitud_c7d839_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="complaintphoto",
            index=models.Index(
                fields=["complaint", "photo_type"],
                name="complaint_p_complai_f75555_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="complaintphoto",
            index=models.Index(
                fields=["uploaded_at"], name="complaint_p_uploade_505d98_idx"
            ),
        ),
    ]
