# Generated by Django 5.2.12 on 2026-03-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("complaints", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="address",
            field=models.TextField(
                blank=True,
                help_text="Human-readable address from reverse geocoding",
                null=True,
            ),
        ),
    ]
