# Generated by Django 5.2.12 on 2026-03-08 17:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("staff", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PickupRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_id",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        help_text="Unique pickup request identifier (auto-generated)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "waste_type",
                    models.CharField(
                        choices=[
                            ("general", "General Waste"),
                            ("recyclable", "Recyclable"),
                            ("organic", "Organic Waste"),
                        ],
                        help_text="Type of waste to be collected",
                        max_length=20,
                    ),
                ),
                (
                    "preferred_date",
                    models.DateField(
                        help_text="Preferred pickup date (must be at least 24 hours in future)"
                    ),
                ),
                (
                    "preferred_time",
                    models.TimeField(
                        blank=True,
                        help_text="Preferred pickup time (optional)",
                        null=True,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Latitude coordinate (-90 to 90)",
                        max_digits=9,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Longitude coordinate (-180 to 180)",
                        max_digits=9,
                    ),
                ),
                ("address", models.TextField(help_text="Pickup address")),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes or instructions (optional, min 10 characters)",
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(10)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("scheduled", "Scheduled"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Current status of the pickup request",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when request was created",
                    ),
                ),
                (
                    "scheduled_date",
                    models.DateField(
                        blank=True, help_text="Actual scheduled pickup date", null=True
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when pickup was completed",
                        null=True,
                    ),
                ),
                (
                    "assigned_staff",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff member assigned to this pickup",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_pickups",
                        to="staff.staffmember",
                    ),
                ),
                (
                    "citizen",
                    models.ForeignKey(
                        help_text="Citizen who requested the pickup",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pickup_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pickup Request",
                "verbose_name_plural": "Pickup Requests",
                "db_table": "pickup_requests",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["request_id"], name="pickup_requ_request_b3a494_idx"
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="pickup_requ_status_7b25c2_idx",
                    ),
                    models.Index(
                        fields=["citizen", "status"],
                        name="pickup_requ_citizen_730172_idx",
                    ),
                    models.Index(
                        fields=["preferred_date"], name="pickup_requ_preferr_dee2ae_idx"
                    ),
                    models.Index(
                        fields=["latitude", "longitude"],
                        name="pickup_requ_latitud_ba96c8_idx",
                    ),
                ],
            },
        ),
    ]
